version: "2.2"
services:
  iris-shared:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iris-shared
    ports:
      - 52773:52773
      - 1972:1972
    volumes:
      - ./shared:/shared
